name: proton-mail
icon: snap/gui/proton-mail.svg
summary: Proton Mail desktop application.
version: 1.1.1
description: |
  Proton desktop application for Proton Mail and Proton Calendar.

website: https://proton.me/mail
contact: https://github.com/pedro-avalos/proton-mail-snap/issues
issues: https://github.com/pedro-avalos/proton-mail-snap/issues
source-code: https://github.com/ProtonMail/inbox-desktop

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  proton-mail:
    command: launcher
    desktop: usr/share/applications/proton-mail.desktop
    environment:
      DISABLE_WAYLAND: 1
    extensions:
      - gnome
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - browser-support
      - gsettings
      - home
      - removable-media
      - hardware-observe  # NOTE: used to detect security keys
      - u2f-devices       # TODO: Request auto-connect
      - network

parts:
  launcher:
    plugin: dump
    source: launcher
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/

  proton-mail:
    plugin: dump
    source-type: deb
    source: https://proton.me/download/mail/linux/${SNAPCRAFT_PROJECT_VERSION}/ProtonMail-desktop-beta.deb
    source-checksum: sha512/1a98968a675ddebdf54e19680108f36920dfbbe291a1f6cd2182fd30064b2a741022884143a36f99c8a5c1f0643faaf0cfc412b1f26f6ef51f15bec5267366ef
    prime:
      - -usr/lib/proton-mail/chrome-sandbox
