name: proton-mail
icon: snap/gui/proton-mail.svg
summary: Proton Mail desktop application.
version: 1.0.5
description: |
  Proton desktop application for Proton Mail and Proton Calendar.

website: https://proton.me/mail
contact: https://github.com/pedro-avalos/proton-mail-snap/issues
issues: https://github.com/pedro-avalos/proton-mail-snap/issues
source-code: https://github.com/ProtonMail/inbox-desktop

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  proton-mail:
    command: usr/bin/proton-mail --no-sandbox
    desktop: usr/share/applications/proton-mail.desktop
    extensions:
      - gnome
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - browser-support
      - gsettings
      - home
      - removable-media
      - hardware-observe  # NOTE: used to detect security keys
      - u2f-devices  # TODO: Request auto-connect
      - network

parts:
  proton-mail:
    plugin: dump
    source-type: deb
    source: https://proton.me/download/mail/linux/ProtonMail-desktop-beta.deb
    source-checksum: sha512/108e434004b323d63f3240f86f8c6e13d0e42d09a59846a8d04b44914927985e93e68ca11ca110581186fc663b28e5eec6d3b49751c0eca9e04f0dea3cf753b3
    prime:
      - -usr/lib/proton-mail/chrome-sandbox
