name: proton-mail
icon: snap/gui/proton-mail.svg
summary: Proton Mail desktop application.
version: 1.2.4
license: GPL-3.0
description: |
  NOTE: This is a wrapper of the official package, but it is not verified,
  affiliated with, or supported by Proton AG.

  Proton desktop application for Proton Mail and Proton Calendar.

  To use security keys, connect the `hardware-observe` and `u2f-devices`
  interfaces.

  `sudo snap connect proton-pass:hardware-observe`

  `sudo snap connect proton-pass:u2f-devices`

website: https://proton.me/mail
contact: https://github.com/pedro-avalos/proton-mail-snap/issues
issues: https://github.com/pedro-avalos/proton-mail-snap/issues
source-code: https://github.com/ProtonMail/inbox-desktop

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  proton-mail:
    command: launcher
    desktop: usr/share/applications/proton-mail.desktop
    environment:
      DISABLE_WAYLAND: 1
    extensions:
      - gnome
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - browser-support
      - gsettings
      - home
      - removable-media
      - hardware-observe
      - u2f-devices
      - network

parts:
  launcher:
    plugin: dump
    source: launcher
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/

  proton-mail:
    plugin: dump
    source-type: deb
    source: https://proton.me/download/mail/linux/${SNAPCRAFT_PROJECT_VERSION}/ProtonMail-desktop-beta.deb
    source-checksum: sha512/a439906d06d6b46505bae017d3152ae2341e3c0ef3588037323484b29238f6be282af4c0da1779142c10b1a210bbd0480e35e15b0b754e9b7868bba6d00e6d0a
    prime:
      - -usr/lib/proton-mail/chrome-sandbox
